# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "heater_controller"
  config.vm.box_url = "heater_controller.box"
  config.vm.network "public_network"
  config.vm.base_mac = nil
  config.vm.provision :shell, args: ENV['ENV'], run: "always", path: "../shell_scripts/startup.sh"
end
